modLoader = "javafml"
loaderVersion = "*"
license = "GPL3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Topodic"
description = "No more cramped enchanting rooms!"
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[mixins]]
config = "uncramped-enchantment-common.mixins.json"

[[mixins]]
config = "uncramped-enchantment-neoforge.mixins.json"